# Generated by Django 6.1.1 on 2026-10-06 22:46

import apps.turnos.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('F5-A', 'Fútbol 5 - A'), ('F5-B', 'Fútbol 5 - B')], max_length=10, unique=True, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField(default='09:00', verbose_name='Horario inicio')),
                ('horario_fin', models.TimeField(default='23:00', verbose_name='Horario fin')),
                ('duracion_turno_min', models.PositiveIntegerField(default=60, verbose_name='Duración del turno (min)')),
                ('plazo_vencimiento_h', models.PositiveIntegerField(default=24, verbose_name='Plazo de vencimiento (h antes del turno)')),
                ('plazo_cancelacion_h', models.PositiveIntegerField(default=24, verbose_name='Plazo de cancelación libre (h antes del turno)')),
                ('anticipacion_max_dias', models.PositiveIntegerField(default=30, verbose_name='Anticipación máxima para reservar (días)')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('rol', models.CharField(choices=[('CLIENTE', 'Cliente'), ('ADMIN', 'Administrador')], default='CLIENTE', max_length=10, verbose_name='Rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', apps.turnos.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('F5', 'Fútbol 5'), ('F7', 'Fútbol 7')], max_length=2, verbose_name='Tipo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12, verbose_name='Estado')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('confirmada_en', models.DateTimeField(blank=True, null=True, verbose_name='Confirmada en')),
                ('cancelada_en', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada en')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReservaCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('ocupando', models.BooleanField(default=True, verbose_name='Ocupando')),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupaciones', to='turnos.cancha')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupaciones', to='turnos.reserva')),
            ],
            options={
                'verbose_name': 'Ocupación',
                'verbose_name_plural': 'Ocupaciones',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='canchas',
            field=models.ManyToManyField(related_name='reservas', through='turnos.ReservaCancha', to='turnos.cancha', verbose_name='Canchas'),
        ),
        migrations.AddConstraint(
            model_name='reservacancha',
            constraint=models.UniqueConstraint(condition=models.Q(('ocupando', True)), fields=('cancha', 'fecha', 'hora_inicio'), name='slot_ocupado_unico'),
        ),
    ]
